In [2]:
import open3d as o3d
import numpy as np
import os

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Convert D-FAUST dataset into .ply file

In [2]:
file_path = "/usr/stud/srinivaa/code/CaDeX/resource/data/Humans/D-FAUST/50002_hips/pcl_seq/00000003.npz"
data = np.load(file_path)
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(data['points'])
o3d.io.write_point_cloud("data_3.ply", pcd)

True

Get the attributes of pcl_seq

In [3]:
for i in data.files:
    print(i)

points
loc
scale


Get the attributes of points_seq

In [4]:
points_seq = np.load("/usr/stud/srinivaa/code/CaDeX/resource/data/Humans/D-FAUST/50002_chicken_wings/points_seq/00000000.npz")
for i in points_seq.files:
    print(i)

points
occupancies
loc
scale


Check the size of total dataset

In [34]:
path, dirs, files = next(os.walk("/usr/stud/srinivaa/code/CaDeX/resource/data/Humans/D-FAUST"))
total_file_size = 0

for i in range(len(dirs)): 
    if(dirs[i] != '50004_chicken_wings' and dirs[i] != '50020_hips' and dirs[i] != '50025_shake_arms' and dirs[i] != '50020_running_on_spot' and dirs[i] != '50007_light_hopping_loose'):
        path_i,dirs_i,files_i = next(os.walk(os.path.join(path,dirs[i],'points_seq')))
        total_file_size += len(files_i)

In [35]:
total_file_size

39920

In [32]:
path, dirs, files = next(os.walk("/usr/stud/srinivaa/code/CaDeX/resource/data/Humans/D-FAUST"))
total_file_size = 0

for i in range(len(dirs)): 
    if(dirs[i] != '50002_light_hopping_loose' and dirs[i] != '50004_punching' and dirs[i] != '50007_shake_shoulders' and dirs[i] != '50009_chicken_wings' and dirs[i] != '50020_chicken_wings' and dirs[i] != '50022_light_hopping_loose' and dirs[i] != '50025_light_hopping_loose' and dirs[i] != '50026_shake_arms' and dirs[i] != '50027_shake_shoulders' and dirs[i] != '50004_chicken_wings' and dirs[i] != '50020_hips' and dirs[i] != '50025_shake_arms' and dirs[i] != '50020_running_on_spot' and dirs[i] != '50007_light_hopping_loose'):
        path_i,dirs_i,files_i = next(os.walk(os.path.join(path,dirs[i],'points_seq')))
        total_file_size += len(files_i)

In [33]:
total_file_size

37867

## Study Deformation_Things4D dataset

In [14]:
#Load the correspondences
corr_data = np.load("/usr/stud/srinivaa/code/CaDeX/resource/data/stapler/0001art/implicit/0001art0000_0.npz")

In [15]:
for i in corr_data.files:
    print(i)

uni_xyz
uni_occ
nss_xyz
nss_occ


In [24]:
corr_data['nss_xyz']

array([[-0.07336, -0.2279 , -0.03485],
       [-0.03506, -0.07654, -0.02345],
       [-0.0365 , -0.05307,  0.1749 ],
       ...,
       [ 0.01872, -0.1226 , -0.1976 ],
       [-0.0184 , -0.175  , -0.03897],
       [-0.04028, -0.344  ,  0.2283 ]], dtype=float16)

In [25]:
np.max(corr_data['nss_occ'])

0.07965

In [32]:
shape_net_points = np.load("/usr/stud/srinivaa/code/occupancy_networks/data/ShapeNet/02958343/1a0bc9ab92c915167ae33d942430658c/points.npz")
for i in shape_net_points.files:
    print(i)

points
occupancies
loc
scale


In [33]:
shape_net_points['occupancies']

array([  0,  96, 128, ...,   0,   1,  33], dtype=uint8)

In [30]:
shape_net_data = np.load("/usr/stud/srinivaa/code/occupancy_networks/data/ShapeNet/02958343/1a0bc9ab92c915167ae33d942430658c/pointcloud.npz")
# points = shape_net_data['points']
# #normals = np.zeros(np.shape(points))
# loc = np.array([0.0,0.0,0.0])
# scale = np.array([0.0])

for i in shape_net_data.files:
    print(i)

points
normals
loc
scale


In [31]:
shape_net_data['normals']

array([[ 0.27497026,  0.05263436,  0.96001093],
       [ 0.15308898, -0.1651738 ,  0.97431072],
       [ 0.43321644, -0.14137259,  0.89013331],
       ...,
       [ 0.78466997,  0.15450936,  0.60034981],
       [ 0.82211854,  0.32468638,  0.46765356],
       [ 0.90825315,  0.30035198,  0.29131582]])

In [8]:
np.savez("/usr/stud/srinivaa/code/occupancy_networks/data/ShapeNet/02958343/1a0bc9ab92c915167ae33d942430658c/pointcloud.npz",points = points,normals=normals,loc=loc,scale=scale)

In [25]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(shape_net_data['points'])
pcd.normals = o3d.utility.Vector3dVector(np.zeros(
    (1, 3)))
normals = pcd.estimate_normals()


array([[ 0.27497026,  0.05263436,  0.96001093],
       [ 0.15308898, -0.1651738 ,  0.97431072],
       [ 0.43321644, -0.14137259,  0.89013331],
       ...,
       [ 0.78466997,  0.15450936,  0.60034981],
       [ 0.82211854,  0.32468638,  0.46765356],
       [ 0.90825315,  0.30035198,  0.29131582]])

In [39]:
radii = [0.005, 0.01, 0.02, 0.04]
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
    pcd, o3d.utility.DoubleVector(radii))
#o3d.visualization.draw_geometries([pcd, rec_mesh])


In [40]:
rec_mesh

TriangleMesh with 6890 points and 9263 triangles.

In [41]:
o3d.io.write_triangle_mesh("mesh.off",mesh)

True